allow-lan: true
log-level: silent
tcp-concurrent: true
dns:
  enable: true
  prefer-h3: false
  ipv6: false
geodata-mode: false
geodata-loader: memconservative
geox-url:
  mmdb: "https://raw.githubusercontent.com/Loyalsoldier/geoip/release/Country.mmdb"
  asn: "https://raw.githubusercontent.com/Loyalsoldier/geoip/release/Country-asn.mmdb"
